# tasks file for virtualenv
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: virtualenv_dependencies
  tags:
    - configuration
    - virtualenv
    - virtualenv-install
    - virtualenv-install-dependencies

- name: install
  pip:
    name: "{{ item }}"
    state: latest
  with_items: virtualenv_pip_dependencies
  tags:
    - configuration
    - virtualenv
    - virtualenv-install
