# tasks file for virtualenv
---
- name: install dependencies
  apt:
    name: "{{ virtualenv_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - virtualenv
    - virtualenv-install
    - virtualenv-install-dependencies

- name: install
  pip:
    name: "{{ virtualenv_pip_dependencies }}"
    state: latest
    executable: "pip{{ virtualenv_python_version | string }}"
  tags:
    - configuration
    - virtualenv
    - virtualenv-install
