# tasks file
---
- name: install | native
  ansible.builtin.import_tasks: install-native.yml
  when: virtualenv_install_method == 'native'
  tags:
    - configuration
    - virtualenv
    - virtualenv-install-native

- name: install | pip
  ansible.builtin.import_tasks: install-pip.yml
  when: virtualenv_install_method == 'pip'
  tags:
    - configuration
    - virtualenv
    - virtualenv-install-pip

- name: verify
  ansible.builtin.command: >
    virtualenv --version
  changed_when: false
  tags:
    - configuration
    - virtualenv
    - virtualenv-install
    - virtualenv-install-verify
